# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='名前')),
            ],
            options={
                'verbose_name_plural': '婚約達',
                'verbose_name': '婚約',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('name_yomi', models.CharField(max_length=200, verbose_name='読み')),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('sex', models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性別')),
                ('dieday', models.DateField(blank=True, null=True, verbose_name='没年月日')),
                ('marriage_flg', models.BooleanField(default=False, verbose_name='婚約者フラグ')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_people', to='people.People', verbose_name='父')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_people', to='people.People', verbose_name='母')),
            ],
            options={
                'verbose_name_plural': '人々',
                'verbose_name': '人',
            },
        ),
        migrations.AddField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband_people', to='people.People', verbose_name='夫'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife_people', to='people.People', verbose_name='妻'),
        ),
    ]
