# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('birthday', models.DateField(verbose_name='誕生日')),
                ('sex', models.NullBooleanField(choices=[(None, ''), (True, '男'), (False, '女')], default=None, verbose_name='性別')),
                ('dieday', models.DateField(blank=True, verbose_name='没年月日')),
                ('marriage_flg', models.BooleanField(default=False, verbose_name='婚約者フラグ')),
                ('generation', models.PositiveIntegerField(verbose_name='世代')),
                ('marriage', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='marriage_people', to='people.People', verbose_name='婚約者')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_people', to='people.People', verbose_name='親')),
            ],
            options={
                'verbose_name_plural': '人々',
                'verbose_name': '人',
            },
        ),
    ]
