# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='generation',
        ),
    ]
