# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_people_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='dieday',
            field=models.DateField(blank=True, null=True, verbose_name='没年月日'),
        ),
        migrations.AlterField(
            model_name='people',
            name='marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marriage_people', to='people.People', verbose_name='婚約者'),
        ),
        migrations.AlterField(
            model_name='people',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_people', to='people.People', verbose_name='親'),
        ),
    ]
