# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161211_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')], default=True, verbose_name='性別'),
        ),
    ]
